---
- name: Preparar mi VM
  hosts: webservers
  remote_user: "{{ vm_user }}"
  become: true
  vars_files:
    - vars/vars.yaml
  tasks:
    - name: Upgrade VM
      include_tasks: tasks/01_appWeb.yaml
    - name: Apache Install
      include_tasks: tasks/02_Apache.yaml
    - name: DO SSL
      include_tasks: tasks/03_CertificadoSSL
